export const URI = 'URI';
export const GET_ALL_POST = 'GET_ALL_POST';
export const GET_ERR = 'GET_ERR';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'
export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAILURE = 'POST_UPDATE_FAILURE';
export const DELETE_USER = "DELETE_USER";
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_CURRENT_USER_SUCCESS = "DELETE_CURRENT_USER_SUCCESS";
export const DELETE_CURRENT_USER_FAILED = "DELETE_CURRENT_USER_FAILED";
export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";
export const ADD_COMMENT = "ADD_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAIL = 'EDIT_COMMENT_FAIL';
export const DELETE_COMMENT = 'DELETE_COMMENT';


